[package]
name = "crypto-transform-hub"
version = "0.1.0"
edition = "2021"

[dependencies]
redpanda-transform-sdk = "0.2.0"
serde = {version = "1.0.197", features = ["derive"]}
serde_json = "1.0.115"
# samsa = "*"
# tokio = { version = "1.37.0", features = ['full'] }
# tokio-stream = "0.1.15"
